import type { Metadata } from "next";
import ".././globals.css";
import QueryProvider from "../components/queryProviders/QueryProvider";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AuthLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className="max-w-full min-h-screen bg-white flex">
                {/* <section className="mx-auto max-w-lg text-center">
                    <h1 className="text-2xl font-bold sm:text-3xl">Welcome back, Login!</h1>
                    <p className="mt-4 text-gray-500">
                        Login to your account to continue
                    </p>
                </section> */}

                <section className="max-w-full w-full flex flex-col justify-center items-center ">
                    <div className="mx-auto max-w-full w-full text-center">
                        <h1 className="text-2xl font-bold sm:text-3xl">Welcome back, Login!</h1>
                        <p className="mt-4 text-gray-500">
                            Login to your account to continue
                        </p>
                    </div>
                    <QueryProvider>
                        {children}
                    </QueryProvider>
                </section>

                <section className="relative max-w-full w-full">
                    <img
                        src="https://www.kppmining.com/assets/images/kpp-home-banner.png"
                        alt="image"
                        className="w-full max-w-full h-full object-cover"
                    />
                    <div className="absolute inset-0 bg-black opacity-60"></div>
                </section>
            </body>
        </html>
    );
}
